# File to check the SYSTEM UPTIME of all the hosts defined in the 'servers' group (in inventory.ini). 

# To run : ansible-playbook -i inventory.ini uptime_check.yml

- name: Check System Uptime
  hosts: servers
  gather_facts: no
  tasks:
    - name: Run uptime command
      command: uptime
      register: uptime_output

    - name: Display uptime result
      debug:
        msg: "System Uptime: {{ uptime_output.stdout }}"
